name: "Update Total Clones Badge"

# Trigger every day at midnight UTC and manually via workflow_dispatch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  aggregate-clones:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository so we can update the badge file
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Aggregate clones across all repos and generate JSON for Shields
      - name: Fetch clone stats & write badge JSON
        id: sum
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 2.1. List all repositories for the current user
            const repos = await github.paginate(
              github.rest.repos.listForUser,
              { username: context.repo.owner, per_page: 100 }
            );

            // 2.2. Fetch and sum clone counts (last 14 days per-day stats)
            let totalClones = 0;
            for (const repo of repos) {
              const { data } = await github.rest.repos.getClones({
                owner: context.repo.owner,
                repo: repo.name,
                per: 'day'
              });
              totalClones += data.clones.reduce((sum, entry) => sum + entry.count, 0);
            }

            // 2.3. Prepare Shields endpoint JSON
            const badge = {
              schemaVersion: 1,
              label: 'total clones',
              message: String(totalClones),
              color: 'blue'
            };

            // 2.4. Write badge JSON file to 'badges/total-clones.json'
            const fs = require('fs');
            fs.mkdirSync('badges', { recursive: true });
            fs.writeFileSync(
              'badges/total-clones.json',
              JSON.stringify(badge, null, 2)
            );

            // 2.5. Return total for use in commit message
            return totalClones;

      # 3. Commit and push only if badge JSON changed
      - name: Commit & push badge update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/total-clones.json
          # Commit only when diffs exist
          git diff --quiet || git commit -m "chore: update total clones to ${{ steps.sum.outputs.result }}"
          git push
